# Generated by Django 4.1.7 on 2023-03-18 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_order_status_alter_design_desc_alter_design_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='trending',
            new_name='trending_category',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='ccost',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='cname',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='cnumber',
            new_name='customer_number',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='cproducts',
            new_name='products',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pdesc',
            new_name='product_description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pimage',
            new_name='product_image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pname',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='ptrending',
            new_name='trending_product',
        ),
    ]
