# Generated by Django 4.1.7 on 2023-03-18 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_rename_desc_category_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='trending_category',
        ),
    ]
