# Generated by Django 4.1.7 on 2023-03-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_remove_category_trending_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_cost',
            field=models.IntegerField(null=True),
        ),
    ]
