# Generated by Django 4.1.7 on 2023-03-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_product_product_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_kg',
            field=models.IntegerField(null=True),
        ),
    ]
