# Generated by Django 4.1.7 on 2023-03-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_product_product_kg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='key',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='pics/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_kg',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
