# Generated by Django 4.1.7 on 2023-03-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_remove_product_key_alter_product_product_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('fnumber', models.IntegerField()),
                ('feedback', models.TextField()),
            ],
        ),
    ]
