# Generated by Django 4.1.7 on 2023-03-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='fstatus',
            field=models.BooleanField(default=False),
        ),
    ]
