# Generated by Django 4.1 on 2023-04-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_feedback_fstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cost',
            new_name='total_cost',
        ),
        migrations.AddField(
            model_name='order',
            name='total_number_of_product',
            field=models.IntegerField(default=1),
        ),
    ]
