# Generated by Django 4.1.7 on 2023-05-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_rename_cost_order_total_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.CharField(default='12-02-2023', max_length=30),
        ),
    ]
