# Generated by Django 4.1.7 on 2023-05-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_alter_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='fname',
            field=models.CharField(editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='fnumber',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='fstatus',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_number',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.CharField(editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_cost',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_number_of_product',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
