# Generated by Django 4.1.7 on 2023-05-04 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_alter_feedback_feedback_alter_feedback_fname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='time',
        ),
    ]
