# Generated by Django 4.1.7 on 2023-05-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='fname',
            field=models.CharField(editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='fnumber',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_number',
            field=models.IntegerField(editable=False),
        ),
    ]
