# Generated by Django 4.1.7 on 2023-05-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_alter_order_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='page_show',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_number',
            field=models.IntegerField(),
        ),
    ]
