# Generated by Django 4.1.7 on 2023-05-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_alter_feedback_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='fstatus',
            new_name='feedback_status',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='page_show',
            new_name='show_in_page',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='fnumber',
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedbacker_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedbacker_number',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(default=''),
        ),
    ]
