# Generated by Django 4.1.7 on 2023-05-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_rename_fstatus_feedback_feedback_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedbacker_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedbacker_number',
            field=models.IntegerField(editable=False),
        ),
    ]
